### ISSUE TITLE
Nix package

### ISSUE THREAD

**Issue by lboklin** [TiddlyWiki/TiddlyDesktop#106]
I have been unsuccessful in building and running this from source on NixOS, mostly because of a lack of experience with NodeJS and insufficient proficiency with Nix. 

If someone knowledgeable in both NodeJS and Nix would consider writing a default.nix for this, that would be great.

**Comment by emmanuelrosa** [comment]
I have a Nix package: https://github.com/emmanuelrosa/erosanix/blob/master/pkgs/tiddlydesktop.nix

**Comment by Jermolene** [comment]
Thanks @emmanuelrosa that's helpful. Would it be useful to add it to this repo, along with a note in the readme?

**Comment by emmanuelrosa** [comment]
Thank you for noticing that error. The fix is in #263
