### ISSUE TITLE
Feature request: new tiddlywiki

### ISSUE THREAD

**Issue by jeancf** [TiddlyWiki/TiddlyDesktop#134]
When the user selects the "New Tiddlywiki..." option, a dialog box opens asking where the new file must be placed and what name it should be given.
Then TiddlyDesktop downloads an empty wiki from the web site to the designated location, renames it and opens it.

**Comment by jdlrobson** [comment]
I hit this one recently! It was a barrier for entry for someone (And for an inexperienced me!) who I was introducing to it. A one click button would be great!

**Comment by Jermolene** [comment]
Thanks @jdlrobson, much appreciate the feedback. I will soon put some work into a TiddlyDesktop update.

**Comment by intranetmouse** [comment]
Is this completed now?  I just tried this in 0.0.14 and it seems to work, unless I am not understanding the requested feature.

**Comment by Jermolene** [comment]
Thanks @intranetmouse it was indeed implemented in 68ed5f06f2ed3ff106f5d8f20e35c799cc11e894
