### ISSUE TITLE
ZIP files do not include executable information for Linux

### ISSUE THREAD

**Issue by sduensin** [TiddlyWiki/TiddlyDesktop#208]
Unzipping the Linux distribution leaves all the binaries un-executable.  Since nw tries to execute other things, it's like playing whack-a-mole to make it run.  Tarball?

**Comment by jerrywham** [comment]
Open a terminal in the folder where you unzip all the binaries then run `./nw`.
Exemple : we consider that the folder is `/home/youraccount/tiddlywiki`
```bash
cd /home/youraccount/tiddlywiki
./nw
```
You can do a launcher to avoid to use terminal.

**Comment by Jermolene** [comment]
Thanks @sduensin @jerrywham, and apologies for the late reply (I was ill over the summer).

I can certainly look at making a tarball instead of a zip file, or do other zip utilities preserve executable information?

**Comment by asheingold** [comment]
@Jermolene Would it be a good idea to create a package for Linux / Ubuntu distributions? I'd package it for release, but don't know if it's actually needed / wanted.

**Comment by Jermolene** [comment]
> @Jermolene Would it be a good idea to create a package for Linux / Ubuntu distributions? I'd package it for release, but don't know if it's actually needed / wanted.

Hi @asheingold I'm not familiar with Linux, but if making a package makes things easier for end users, then I'd be very much in favour.

At the moment we don't have CI set up for TiddlyDesktop, so I build it manually on my Mac, and would need to be able to run the Linux packaging steps.

**Comment by Jermolene** [comment]
Fixed in #309
