### ISSUE TITLE
Crashes on Apple Silicon

### ISSUE THREAD

**Issue by haegar33** [TiddlyWiki/TiddlyDesktop#250]
Apple MacBook Pro from 2021 with MacOS 15.2
App is closed after a few seconds, no crash report but only a njw diagnostic:

`Date/Time:        2022-04-06 15:21:35.763 +0200
End time:         2022-04-06 15:25:39.227 +0200
OS Version:       macOS 12.2.1 (Build 21D62)
Architecture:     arm64e
Report Version:   35
Incident Identifier: BE44D166-332A-4C30-AF7D-CBB7ED19BB67

Data Source:      Microstackshots
Shared Cache:     5C9FF5DB-8827-329A-8A37-2483935A9EA1 slid base address 0x7ff81bf1c000, slide 0x1bf1c000
Shared Cache:     296EB28E-6AEB-3129-8FA6-FEB92261A4EB slid base address 0x196378000, slide 0x16378000

Command:          nwjs Helper
Path:             /Applications/Office/TiddlyWiki.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper
Identifier:       io.nwjs.nw.helper
Version:          41.0.2272.76 (2272.76)
Architecture:     x86_64 (translated)
Parent:           UNKNOWN [943]
PID:              945

Event:            wakeups
Action taken:     none
Wakeups:          45001 wakeups over the last 243 seconds (185 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:    45000
Limit duration:   300s
Wakeups caused:   45001
Wakeups duration: 243s
Duration:         243.46s
Duration Sampled: 240.89s
Steps:            35

Hardware model:   MacBookPro18,1
Active cpus:      10
HW page size:     16384
VM page size:     16384

Fan speed:        0 rpm
Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  22.21 GB/460.43 GB, low space threshold 3072 MB

Heaviest stack for the target process:
  26  thread_start + 15 (libsystem_pthread.dylib + 8207) [0x7ff81c23600f]
  26  _pthread_start + 125 (libsystem_pthread.dylib + 25844) [0x7ff81c23a4f4]
  22  ??? (nwjs Framework + 1232123) [0x111b4fcfb]
  15  ??? (nwjs Framework + 23080781) [0x113025f4d]
  15  ??? (nwjs Framework + 23081113) [0x113026099]
  15  ??? (nwjs Framework + 1214203) [0x111b4b6fb]
  15  ??? [0x7ff8ac7ca940]

Powerstats for:   nwjs Helper [945]
UUID:             09DC9F8E-3B87-3D7A-B8EB-6BCB98062210
Path:             /Applications/Office/TiddlyWiki.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper
Identifier:       io.nwjs.nw.helper
Version:          41.0.2272.76 (2272.76)
Shared Cache:     5C9FF5DB-8827-329A-8A37-2483935A9EA1 slid base address 0x7ff81bf1c000, slide 0x1bf1c000
Architecture:     x86_64 (translated)
Parent:           UNKNOWN [943]
UID:              501
Footprint:        399.67 MB -> 490.05 MB (+90.38 MB)
Pageins:          689 pages
Start time:       2022-04-06 15:21:37.148 +0200
End time:         2022-04-06 15:25:38.035 +0200
Num samples:      35 (100%)
Primary state:    14 samples Non-Frontmost App, Non-Suppressed, Kernel mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:    0 samples Idle, 35 samples Active
Power Source:     0 samples on Battery, 35 samples on AC
  26  thread_start + 15 (libsystem_pthread.dylib + 8207) [0x7ff81c23600f]
    26  _pthread_start + 125 (libsystem_pthread.dylib + 25844) [0x7ff81c23a4f4]
      22  ??? (nwjs Framework + 1232123) [0x111b4fcfb]
        15  ??? (nwjs Framework + 23080781) [0x113025f4d]
          15  ??? (nwjs Framework + 23081113) [0x113026099]
            15  ??? (nwjs Framework + 1214203) [0x111b4b6fb]
              15  ??? [0x7ff8ac7ca940]
                1   <User mode>
`

**Comment by GJRobert** [comment]
I have also raised a similar bug #239

**Comment by Jermolene** [comment]
nwjs doesn't yet have an Apple Silicon build, but it's possible that they've fixed bugs in the most recent Intel build. I'll try to get out an update with the newest nwjs.

**Comment by dixonge** [comment]
As best I can tell, NW.js now has an M1/Silicon build. Should be able to close out this Issue.

**Comment by Jermolene** [comment]
Thanks @dixonge that's great news. I'll try to get an update out soon.

**Comment by GJRobert** [comment]
Downloaded v0.0.15 pre-4 today, it can run like a charm on my Apple Silicon MacBook + Big Sur now. Saving works. Thanks a lot to @Jermolene and other contributors. 💯 ♥

**Comment by Jermolene** [comment]
Thanks @GJRobert I'll close this for now.
