### ISSUE TITLE
Release naming convention issue (prerelease 3 sharing identical file names as prerelease 2)

### ISSUE THREAD

**Issue by gladuser** [TiddlyWiki/TiddlyDesktop#252]
Just a minor detail, but in case it wasn't already addressed...
I would suggest renaming the Prerelease 3 asset file names with "...v0.0.15-prerelease.3.zip" (instead of the current names "...v0.0.15-prerelease.2.zip"

![Prerelease2-3](https://user-images.githubusercontent.com/82974949/172448601-29c643d9-48aa-4978-8556-b19e71db0ea1.png)
)

**Comment by bl4krat** [comment]
And the pre-release 3 version (linux 64bit) still advertises itself as prerelease 2 on the help | information page.

**Comment by Jermolene** [comment]
Thanks @gladuser @bl4krat there's now a new prerelease-4 which should resolve the confusion:

https://github.com/TiddlyWiki/TiddlyDesktop/releases/tag/v0.0.15-prerelease.4
