### ISSUE TITLE
a problem happened in tiddler folder

### ISSUE THREAD

**Issue by joylous** [TiddlyWiki/TiddlyDesktop#254]
I use the extension **Maoxian Web Clipper** in edge for cutting web. It really works and the content can be saved in the setting path including **PIC** attachment, **JSON** info and the **MD** file. Then I open the distribution of tiddlywiki called **tiddlygit** and get the problem. It happened when I restart tiddlygit or its service, that the pics and other files are moved to the tiddler root folder, the pic is 0kb occupied. Anyone knows the reason?

**Comment by Jermolene** [comment]
Hi @joylous thanks for your patience. We can't offer support for tiddlygit here; perhaps @linonetwo can advise the best place to ask.

**Comment by linonetwo** [comment]
@joylous Hey, why not rise issue at https://github.com/tiddly-gittly/TidGi-Desktop ?

**Comment by joylous** [comment]
> @joylous Hey, why not rise issue at https://github.com/tiddly-gittly/TidGi-Desktop ?

I already ask you guys both in the QQ group and [TidGi-Desktop](https://github.com/tiddly-gittly/TidGi-Desktop)  but no response for a long time, then I submit it here and [tiddlywiki](https://talk.tiddlywiki.org/). The problem is solved now.
