### ISSUE TITLE
[Question] How to refresh iframe until success?

### ISSUE THREAD

**Issue by FarukOzderim** [TiddlyWiki/TiddlyDesktop#270]
Hello, 

I am using GitHub and google viewer to host&render pdf in my tiddlywiki [notebook](https://farukozderim.github.io/PhD-Courses/#566-L6-Suffix-Link). There is a bug in viewer that causes fails with iframe loads, and there are [hacks](https://stackoverflow.com/questions/35298724/google-docs-viewer-occasionally-failing-to-load-content-in-iframe) with refresh until success. 

How can I put this in my tiddlywiki notebook? It seems I can do it with javascript tiddys? But not quite sure how to approach it.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/44067394/221630315-f3221397-dd0d-45cd-984c-7fefca6cdc92.png">

**Comment by Jermolene** [comment]
Hi @FarukOzderim it sounds like this is a general TiddlyWiki question, and not specific to TiddlyDesktop. If so, I'd suggest asking over at https://talk.tiddlywiki.org/ for maximum exposure.
