### ISSUE TITLE
Opening .tid files results in window that cannot be closed

### ISSUE THREAD

**Issue by GHExplorer** [TiddlyWiki/TiddlyDesktop#271]
Hi,

This is regarding Windows 10, with the 32-bit version of TiddlyWiki Desktop.

If I click Add wiki file and open a file with a .tid extension, a secondary TiddlyDesktop window pops up, with a kind of Notepad display of the file.

If I try to close this file with the Upper Right X, it won't close.  If I click the Remove button, it seems to click, but doesn't do anything.

It's necessary to use Task Manager, to close all of the open .tid files.  When TiddlyDesktop is run again, those files are still in the Untitled list.

This is the folder I'm opening the files from:

..\..\TiddlyDesktop-win32-v0.0.16\tiddlywiki\editions\dev\tiddlers\new

**Comment by Jermolene** [comment]
Thank you @GHExplorer. The "Add wiki file" option is designed to open TiddlyWiki standalone HTML files, and does not do anything useful function with other file types.  But of course opening an unsupported file shouldn't behave as you have described. I've updated the description of this ticket.

**Comment by GHExplorer** [comment]
Thanks, Jermolene.
