### ISSUE TITLE
The macapplesilicon app reports as been damaged

### ISSUE THREAD

**Issue by braykov** [TiddlyWiki/TiddlyDesktop#277]
I am on MacOS Ventura 13.4, MacBook Pro with M1 Pro chip.
Any of the 17 or 18 macapplesilicon app I try to run, I get a message that the app is "damaged" and I should move it to the Bin.
The mac64 app however, seems to run OK.

**Comment by xpucadad** [comment]
Any ETA on a fix?

**Comment by srbt1** [comment]
Same issue here, unfortunately, with macOS 13.4.1 and an M1 pro.

**Comment by Jermolene** [comment]
Apologies @braykov @xpucadad @srbt1 – this is a known issue, and I'm working on it. I'm closing this in favour of the earlier report in ticket #276.
