### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cukal** [TiddlyWiki/TiddlyDesktop#279]
Non Issue.

I started a TiddlyWiki file way back in 2008 using a customised TW template, it contains so much personal work & coding related documentation I use it on a daily basis, upgraded it a few times over the years and at one point I switched to a fixed Firefox version & TiddlySaver.jar, this setup worked for years. TW is one of the main cornerstones of my workflow. This weekend I _foolishly_ upgraded from Monterey to Ventura and my TW setup fails miserably...

Downloaded TiddlyDesktop and imported my 2008 TW file and it is staring back at me in full. functional. glory.
I'm speechless.

Thanks!

**Comment by Jermolene** [comment]
Thank you @cukal much appreciated. The mention of TiddlySaver.jar is particularly nostalgic, that was a long time ago!
