### ISSUE TITLE
Wrong version number for v0.0.19 builds

### ISSUE THREAD

**Issue by adithyasunil26** [TiddlyWiki/TiddlyDesktop#291]
The `v0.0.19` release builds have `v0.0.18` in their filename instead of `v0.0.19`.

**Comment by Jermolene** [comment]
Thanks @adithyasunil26 

@rmunn presumably I should have manually updated the version number before creating the tag?

**Comment by Jermolene** [comment]
I've just uploaded v0.0.20 which will be available here once the build is complete:

https://github.com/TiddlyWiki/TiddlyDesktop/releases/tag/v0.0.20

**Comment by rmunn** [comment]
> @rmunn presumably I should have manually updated the version number before creating the tag?

Yes. The idea is:

- Update the version number in package.json, plus any other changes that should be included.
- Make a commit and push it.
- Tag that commit with v#.#.#, the version number you just updated in package.json.
- Push that tag and a draft release will be created.
- Edit the draft release: add release notes, edit whatever else might need to be changed. Download its build files and test them.
- Switch the draft release to be a public release once it's tested and ready.

**Comment by Jermolene** [comment]
Thanks @rmunn I've updated the readme with those instructions.
