### ISSUE TITLE
TiddlyDesktop App favicon in the list of TiddlyWiki's

### ISSUE THREAD

**Issue by frakier** [TiddlyWiki/TiddlyDesktop#301]
So I want a icon to show up in TiddlyDesktop where the dotted circles are. I know it works, Grok Tiddlywiki does it and have seen others that do this. I followed the instructions on the [Tiddlywik](https://tiddlywiki.com) for adding a faveicon. Tried it with both a ico and png file in the $:/favicon.ico. Both file types show up in the browser but not in the TiddlyDesktop app. Tried looking at how other tiddlywiki's do this and I see no difference. I have seen others asking about issues similar but the wording for the issue did not see right for a issue report so I started a separate issue.

Started with...
TiddlyDesktop - tiddlydesktop-linux64-v0.0.20
TiddlyWiki - 5.3.5 (Empty TiddlyWiki File)

**Comment by Jermolene** [comment]
Hi @frakier that is strange. Any PNG or JPEG image should work as $:/favicon.ico

Could you perhaps share a JSON file of your $:/favicon.ico tiddler? (Use the "Export" option of the tiddler toolbar)

**Comment by frakier** [comment]
Was playing around experimenting. Downloaded the https://tiddlywiki.com/ site. Deleted the $:/favicon.ico tiddler and dropped my image a png file onto the TiddlyWiki, editied the name hit the check and imported my image as $:/favicon.ico. and it worked. That fave icon replaces the blue cat icon in TiddlyDesktop for the TiddlyWiki.com TiddlyWiki.

**Comment by frakier** [comment]
Figured it out, the problem was the path to where I had the folder was saved in linux. How you ask? Well part of the folder path has [MyProjects] as a part of a folder name. for example: "/home/frakier/ttg/1_[MyProject]/My_tiddlywiki". So no important characters, like [ and ] for example from TiddlyWiki in the folder path.
